name: de-lambda-deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    if: false # this will cause the job to be skipped - delete to enable 
    name: run-tests
    runs-on: ubuntu-latest
    # implement me

  deploy-lambda:
    if: false # this will cause the job to be skipped - delete to enable 
    name: deploy-lambda
    # implement me